### ISSUE TITLE
Missing Attributes toChecksumAddress and ContractFunction

### ISSUE THREAD

**Issue by untdacca** [Omni-Analytics-Group/uniswappeR#3]
Has the documentation changed for any of these functions when compared to the underlying uniswap-python?

ex) toChecksumAddress vs. to_checksum_address
Your original function $Web3$toChecksumAddress isn't found however $Web3$to_checksum_address is.
https://web3py.readthedocs.io/en/latest/web3.main.html#web3.Web3.to_checksum_address

Similarly, ContractFunction hasn't been found when calling uniswap_session.
https://web3py.readthedocs.io/en/latest/web3.contract.html#web3.contract.ContractFunction

<img width="512" alt="Screen Shot 2023-03-24 at 8 40 46 AM" src="https://user-images.githubusercontent.com/76915445/227524161-c3e4dc78-1d5a-48d7-8b4f-b095668b50bd.png">

**Comment by yogesh-bansal** [comment]
The issue is open with uniswap-python, In the meantime, one can get by using the older version of web3.

**Comment by untdacca** [comment]
Brilliant thanks, Yogesh.

**Comment by Fayorsey** [comment]
> The issue is open with uniswap-python, In the meantime, one can get by using the older version of web3.

Do you know what version of web3 works?
