### ISSUE TITLE
Calls to Sushiswap

### ISSUE THREAD

**Issue by untdacca** [Omni-Analytics-Group/uniswappeR#4]
Additional functionality was added to uniswap-python that allows for factory and router customization. 

Is there any way we can use this to access Sushiswap?

**Comment by detectivesmart300** [comment]
Yes, just copy this code into R and change your address and private key and run the function:
 router_contract_addr = '0xd9e1ce17f2641f24ae83637ab66a2cca9c378b9f'
factory_contract_addr = '0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac' 
sushiswap_session <- function (node = get_infura_node(), user_add = NULL, pvt_key = NULL, 
                                       version = 2, factory_contract_addr, router_contract_addr) 
      {
        py_run_string(paste0("import os;os.environ[\"PROVIDER\"] = \"", 
                             node, "\""))
        uniswap <- import("uniswap", convert = FALSE)
        uniswap$Uniswap(user_add, pvt_key, version = version, router_contract_addr = router_contract_addr, factory_contract_addr = factory_contract_addr)
      }
u_w <- sushiswap_session(user_add = CHANGEADDRESS, pvt_key = CHANGEPVTKEY, version = 2)

**Comment by Fayorsey** [comment]
Awesome, will deploy and let you know how it goes.

**Comment by Fayorsey** [comment]
Awesome, thank you. Will deploy it and let you know how it goes.
